/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
//
//import DAO.*;
//import DTO.*;

import DAO.*;
import DTO.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
//import ui.nhanvienForm;

/**
 *
 * @author Hyung
 */
public class DashBoard extends javax.swing.JFrame
{

    private boolean check = true;
    ThiSinhForm thiSinhForm;
    GiaoVienForm giaoVienForm;
    PhongThiForm phongThiForm;
    KhoaThiForm khoaThiForm;
    TrinhDoForm trinhDoForm;
    CaThiForm caThiForm;
    KetQuaForm ketQuaForm;
    KhoaThiDAO khoaThiDAO;
    public static ArrayList<KhoaThiDTO> khoaThiDTOs;
    TrinhDoDAO trinhDoDAO;
    public static ArrayList<TrinhDoDTO> trinhDoDTOs;
    PhongThiDAO phongThiDAO;
    public static ArrayList<PhongThiDTO> phongThiDTOs;
    CaThiDAO caThiDAO;
    public static ArrayList<CaThiDTO> caThiDTOs;
    GiaoVienDAO giaoVienDAO;
    public static ArrayList<GiaoVienDTO> giaoVienDTOs;
    ThiSinhDAO thiSinhDAO;
    public static ArrayList<ThiSinhDTO> thiSinhDTOs;
    PhanCongDAO phanCongDAO;
    public static ArrayList<PhanCongDTO> phanCongDTOs;
    PhieuBaoDuThiDAO phieuBaoDuThiDAO;
    public static ArrayList<PhieuBaoDuThiDTO> phieuBaoDuThiDTOs;
    KetQuaThiDAO ketQuaThiDAO;
    public static ArrayList<KetQuaThiDTO> ketQuaThiDTOs;

    /**
     * Creates new form DashBoard
     */
    public DashBoard()
    {
        thiSinhForm = new ThiSinhForm();
        giaoVienForm = new GiaoVienForm();
        phongThiForm = new PhongThiForm();
        khoaThiForm = new KhoaThiForm();
        trinhDoForm = new TrinhDoForm();
        caThiForm = new CaThiForm();
        ketQuaForm = new KetQuaForm();
        khoaThiDAO = new KhoaThiDAO();
        trinhDoDAO = new TrinhDoDAO();
        phongThiDAO = new PhongThiDAO();
        caThiDAO = new CaThiDAO();
        giaoVienDAO = new GiaoVienDAO();
        thiSinhDAO = new ThiSinhDAO();
        phanCongDAO = new PhanCongDAO();
        phieuBaoDuThiDAO = new PhieuBaoDuThiDAO();
        ketQuaThiDAO = new KetQuaThiDAO();
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DashBoard.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabelMini = new javax.swing.JLabel();
        jLabelClosed = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linehideMenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        btnHidemenu = new javax.swing.JLabel();
        settingLogout = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        thisinhPanel = new javax.swing.JPanel();
        khoathiLabel = new javax.swing.JLabel();
        giangvienPanel = new javax.swing.JPanel();
        trinhdoLabel = new javax.swing.JLabel();
        phongthiPanel = new javax.swing.JPanel();
        cathiLabel = new javax.swing.JLabel();
        hopdongPanel = new javax.swing.JPanel();
        phongthiLabel = new javax.swing.JLabel();
        khachPanel = new javax.swing.JPanel();
        thisinhLabel = new javax.swing.JLabel();
        nhanvienPanel = new javax.swing.JPanel();
        giaovienLabel = new javax.swing.JLabel();
        chiphiPanel = new javax.swing.JPanel();
        ketquaLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelThiSinh = new javax.swing.JPanel();
        jPanelGiangVien = new javax.swing.JPanel();
        jPanelPhongThi = new javax.swing.JPanel();
        jPanelKhoaThi = new javax.swing.JPanel();
        jPanelTrinhDo = new javax.swing.JPanel();
        jPanelCaThi = new javax.swing.JPanel();
        jPanelKetQua = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(212, 236, 189));
        kGradientPanel1.setkStartColor(new java.awt.Color(66, 98, 124));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1250, 700));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1250, 700));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(84, 113, 126));
        kGradientPanel2.setkGradientFocus(1000);
        kGradientPanel2.setkStartColor(new java.awt.Color(84, 113, 126));
        kGradientPanel2.setkTransparentControls(false);
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(1250, 50));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1250, 50));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_minimize_window_48.png"))); // NOI18N
        jLabelMini.setToolTipText("Minimize");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelMiniMouseClicked(evt);
            }
        });
        jLabelMini.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jLabelMiniPropertyChange(evt);
            }
        });
        kGradientPanel2.add(jLabelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 0, 40, 50));

        jLabelClosed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_48.png"))); // NOI18N
        jLabelClosed.setToolTipText("Close");
        jLabelClosed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClosed.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelClosedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLabelClosedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLabelClosedMouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabelClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 0, 40, 50));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(167, 193, 169));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-english-language-40.png"))); // NOI18N
        jLabel4.setToolTipText("");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 242, 249));
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 170, 50));
        jLabel5.getText ();

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(167, 193, 169));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_waving_hand_emoji_32.png"))); // NOI18N
        jLabel6.setText("Xin chào");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 150, 50));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(233, 242, 249));
        jLabel8.setText("<html> <span>QUẢN LÝ THI TIẾNG ANH <span> </html> ");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 50));
        jLabel5.getText ();

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(81, 113, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 650));

        menuIcon.setBackground(new java.awt.Color(66, 98, 124));
        menuIcon.setMinimumSize(new java.awt.Dimension(100, 5));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 650));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehideMenu.setBackground(new java.awt.Color(66, 98, 124));
        linehideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehideMenuLayout = new javax.swing.GroupLayout(linehideMenu);
        linehideMenu.setLayout(linehideMenuLayout);
        linehideMenuLayout.setHorizontalGroup(
            linehideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehideMenuLayout.setVerticalGroup(
            linehideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(linehideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hidemenu.setBackground(new java.awt.Color(66, 98, 124));
        hidemenu.setPreferredSize(new java.awt.Dimension(50, 50));
        hidemenu.setLayout(new java.awt.BorderLayout());

        btnHidemenu.setBackground(new java.awt.Color(66, 98, 124));
        btnHidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_menu_32.png"))); // NOI18N
        btnHidemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHidemenu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnHidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnHidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnHidemenuMouseExited(evt);
            }
        });
        hidemenu.add(btnHidemenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, -1));

        settingLogout.setBackground(new java.awt.Color(66, 98, 124));
        settingLogout.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout settingLogoutLayout = new javax.swing.GroupLayout(settingLogout);
        settingLogout.setLayout(settingLogoutLayout);
        settingLogoutLayout.setHorizontalGroup(
            settingLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        settingLogoutLayout.setVerticalGroup(
            settingLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(settingLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        logout.setBackground(new java.awt.Color(66, 98, 124));
        logout.setPreferredSize(new java.awt.Dimension(50, 50));
        logout.setLayout(new java.awt.BorderLayout());

        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exit_32.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnLogoutMouseExited(evt);
            }
        });
        logout.add(btnLogout, java.awt.BorderLayout.CENTER);

        menuIcon.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        jPanel3.setBackground(new java.awt.Color(81, 113, 131));

        jPanel5.setBackground(new java.awt.Color(81, 113, 131));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 245, 253));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menu");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        thisinhPanel.setBackground(new java.awt.Color(81, 113, 131));
        thisinhPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        khoathiLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        khoathiLabel.setForeground(new java.awt.Color(208, 245, 253));
        khoathiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bookmark-32.png"))); // NOI18N
        khoathiLabel.setText("KHÓA THI");
        khoathiLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        khoathiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        khoathiLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                khoathiLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                khoathiLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                khoathiLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout thisinhPanelLayout = new javax.swing.GroupLayout(thisinhPanel);
        thisinhPanel.setLayout(thisinhPanelLayout);
        thisinhPanelLayout.setHorizontalGroup(
            thisinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khoathiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        thisinhPanelLayout.setVerticalGroup(
            thisinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(khoathiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        giangvienPanel.setBackground(new java.awt.Color(81, 113, 131));
        giangvienPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        trinhdoLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        trinhdoLabel.setForeground(new java.awt.Color(208, 245, 253));
        trinhdoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-level-32.png"))); // NOI18N
        trinhdoLabel.setText("TRÌNH ĐỘ");
        trinhdoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        trinhdoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trinhdoLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                trinhdoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                trinhdoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                trinhdoLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout giangvienPanelLayout = new javax.swing.GroupLayout(giangvienPanel);
        giangvienPanel.setLayout(giangvienPanelLayout);
        giangvienPanelLayout.setHorizontalGroup(
            giangvienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trinhdoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        giangvienPanelLayout.setVerticalGroup(
            giangvienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trinhdoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        phongthiPanel.setBackground(new java.awt.Color(81, 113, 131));
        phongthiPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        cathiLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        cathiLabel.setForeground(new java.awt.Color(208, 245, 253));
        cathiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-time-32.png"))); // NOI18N
        cathiLabel.setText("CA THI");
        cathiLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        cathiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cathiLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cathiLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                cathiLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                cathiLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout phongthiPanelLayout = new javax.swing.GroupLayout(phongthiPanel);
        phongthiPanel.setLayout(phongthiPanelLayout);
        phongthiPanelLayout.setHorizontalGroup(
            phongthiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cathiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        phongthiPanelLayout.setVerticalGroup(
            phongthiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cathiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        hopdongPanel.setBackground(new java.awt.Color(81, 113, 131));
        hopdongPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        phongthiLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        phongthiLabel.setForeground(new java.awt.Color(208, 245, 253));
        phongthiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-room-32.png"))); // NOI18N
        phongthiLabel.setText("PHÒNG THI");
        phongthiLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        phongthiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        phongthiLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                phongthiLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                phongthiLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                phongthiLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hopdongPanelLayout = new javax.swing.GroupLayout(hopdongPanel);
        hopdongPanel.setLayout(hopdongPanelLayout);
        hopdongPanelLayout.setHorizontalGroup(
            hopdongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phongthiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hopdongPanelLayout.setVerticalGroup(
            hopdongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phongthiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        khachPanel.setBackground(new java.awt.Color(81, 113, 131));
        khachPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        khachPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        thisinhLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        thisinhLabel.setForeground(new java.awt.Color(208, 245, 253));
        thisinhLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-staff-32.png"))); // NOI18N
        thisinhLabel.setText("THÍ SINH");
        thisinhLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        thisinhLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thisinhLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                thisinhLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                thisinhLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                thisinhLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout khachPanelLayout = new javax.swing.GroupLayout(khachPanel);
        khachPanel.setLayout(khachPanelLayout);
        khachPanelLayout.setHorizontalGroup(
            khachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thisinhLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        khachPanelLayout.setVerticalGroup(
            khachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thisinhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        nhanvienPanel.setBackground(new java.awt.Color(81, 113, 131));
        nhanvienPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        giaovienLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        giaovienLabel.setForeground(new java.awt.Color(208, 245, 253));
        giaovienLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-customer-32.png"))); // NOI18N
        giaovienLabel.setText("GIÁO VIÊN");
        giaovienLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        giaovienLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giaovienLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                giaovienLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                giaovienLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                giaovienLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout nhanvienPanelLayout = new javax.swing.GroupLayout(nhanvienPanel);
        nhanvienPanel.setLayout(nhanvienPanelLayout);
        nhanvienPanelLayout.setHorizontalGroup(
            nhanvienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giaovienLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nhanvienPanelLayout.setVerticalGroup(
            nhanvienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(giaovienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        chiphiPanel.setBackground(new java.awt.Color(81, 113, 131));
        chiphiPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        ketquaLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        ketquaLabel.setForeground(new java.awt.Color(208, 245, 253));
        ketquaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-result-32.png"))); // NOI18N
        ketquaLabel.setText("KẾT QUẢ");
        ketquaLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        ketquaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ketquaLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                ketquaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                ketquaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                ketquaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout chiphiPanelLayout = new javax.swing.GroupLayout(chiphiPanel);
        chiphiPanel.setLayout(chiphiPanelLayout);
        chiphiPanelLayout.setHorizontalGroup(
            chiphiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ketquaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chiphiPanelLayout.setVerticalGroup(
            chiphiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ketquaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nhanvienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(hopdongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(khachPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(thisinhPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(phongthiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chiphiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(giangvienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(802, 802, 802))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(thisinhPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(giangvienPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phongthiPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hopdongPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(khachPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanvienPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chiphiPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(134, 162, 154));
        jPanel2.setEnabled(false);

        jPanelThiSinh.setLayout(new javax.swing.BoxLayout(jPanelThiSinh, javax.swing.BoxLayout.LINE_AXIS));
        jPanelThiSinh.setVisible (false);

        jPanelGiangVien.setLayout(new javax.swing.BoxLayout(jPanelGiangVien, javax.swing.BoxLayout.LINE_AXIS));
        jPanelGiangVien.setVisible (false);

        jPanelPhongThi.setLayout(new javax.swing.BoxLayout(jPanelPhongThi, javax.swing.BoxLayout.LINE_AXIS));
        jPanelPhongThi.setVisible (false);

        jPanelKhoaThi.setLayout(new javax.swing.BoxLayout(jPanelKhoaThi, javax.swing.BoxLayout.LINE_AXIS));
        jPanelKhoaThi.setVisible (false);

        jPanelTrinhDo.setLayout(new javax.swing.BoxLayout(jPanelTrinhDo, javax.swing.BoxLayout.LINE_AXIS));
        jPanelTrinhDo.setVisible (false);

        jPanelCaThi.setLayout(new javax.swing.BoxLayout(jPanelCaThi, javax.swing.BoxLayout.LINE_AXIS));
        jPanelCaThi.setVisible (false);

        jPanelKetQua.setLayout(new javax.swing.BoxLayout(jPanelKetQua, javax.swing.BoxLayout.LINE_AXIS));
        jPanelKetQua.setVisible (false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1080, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(990, 650));
        jLabel1.setPreferredSize(new java.awt.Dimension(990, 650));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelCaThi, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKhoaThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKhoaThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(650, 655, Short.MAX_VALUE))
            .addComponent(jPanelCaThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelThiSinh.add (thiSinhForm);
        //jPanel10.add(pb);
        jPanelGiangVien.add(giaoVienForm);
        //jPanel7.add(da);
        jPanelPhongThi.add(phongThiForm);
        //jPanel8.add (hd);
        jPanelKhoaThi.add(khoaThiForm);
        //jPanel9.add(bcc);
        jPanelTrinhDo.add(trinhDoForm);
        //jPanel11.add(phucap);
        jPanelCaThi.add(caThiForm);
        jPanelKetQua.add(ketQuaForm);

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 990, 650));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));
        kGradientPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelMiniMouseClicked
    {//GEN-HEADEREND:event_jLabelMiniMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    /**
     *
     * @param hover
     * @param rand
     */
    public void changecolor(JPanel hover, Color rand)
    {
        hover.setBackground(rand);
    }

    public void changecolor1(JLabel hover1, Color rand)
    {
        hover1.setBackground(rand);
    }

    public void clickMenu(JPanel p1, JPanel p2, int numbool)
    {
        if (numbool == 1)
        {
            changecolor(p1, new Color(81, 113, 131));
            changecolor(p2, new Color(66, 98, 124));
        }
    }

    public void changeIcon(JLabel lb, String src)
    {
        ImageIcon ic = new ImageIcon(getClass().getResource(src));
        lb.setIcon(ic);
    }

    public void hideshowMenu(JPanel p, boolean check, JLabel lb)
    {
        if (check == true)
        {
            p.setPreferredSize(new Dimension(50, 650));
            changeIcon(lb, "/img/icons8_back_32.png");
//            p2.setPreferredSize (new Dimension (1200, 650));
        } else
        {
            p.setPreferredSize(new Dimension(260, 650));
            changeIcon(lb, "/img/icons8_menu_32.png");
//            p2.setPreferredSize (new Dimension (990, 650));
        }
    }

    private void jLabelClosedMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseClicked
    {//GEN-HEADEREND:event_jLabelClosedMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClosedMouseClicked

    private void jLabelMiniPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jLabelMiniPropertyChange
    {//GEN-HEADEREND:event_jLabelMiniPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMiniPropertyChange

    private void jLabelClosedMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseEntered
    {//GEN-HEADEREND:event_jLabelClosedMouseEntered
//        changecolor (jLabel3, new Color(232, 68, 82));
    }//GEN-LAST:event_jLabelClosedMouseEntered

    private void jLabelClosedMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseExited
    {//GEN-HEADEREND:event_jLabelClosedMouseExited
//         changecolor (jLabel3, new Color(232, 68, 82));
    }//GEN-LAST:event_jLabelClosedMouseExited

    private void btnHidemenuMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseEntered
    {//GEN-HEADEREND:event_btnHidemenuMouseEntered
        changecolor(linehideMenu, new Color(210, 226, 199));
    }//GEN-LAST:event_btnHidemenuMouseEntered

    private void btnHidemenuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseClicked
    {//GEN-HEADEREND:event_btnHidemenuMouseClicked
        clickMenu(hidemenu, logout, 1);
        if (check == true)
        {
            hideshowMenu(jPanel1, check, btnHidemenu);
//              changeIcon (btnHidemenu, check);
            SwingUtilities.updateComponentTreeUI(this);
            check = false;
        } else
        {
            hideshowMenu(jPanel1, check, btnHidemenu);
//            changeIcon (btnHidemenu, check);
            SwingUtilities.updateComponentTreeUI(this);
            check = true;
        }

    }//GEN-LAST:event_btnHidemenuMouseClicked

    private void btnHidemenuMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseExited
    {//GEN-HEADEREND:event_btnHidemenuMouseExited
        changecolor(linehideMenu, new Color(66, 98, 124));
    }//GEN-LAST:event_btnHidemenuMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseClicked
    {//GEN-HEADEREND:event_btnLogoutMouseClicked
        clickMenu(logout, hidemenu, 1);
        int confirm = JOptionPane.showConfirmDialog(DashBoard.this, "Bạn muốn đăng xuất?",
                "Xác Nhận", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == JOptionPane.OK_OPTION)
        {
            this.dispose(); ////  Exit Program
            LoginForm lg = new LoginForm();
            lg.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseEntered
    {//GEN-HEADEREND:event_btnLogoutMouseEntered
        changecolor(settingLogout, new Color(197, 64, 51));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseExited
    {//GEN-HEADEREND:event_btnLogoutMouseExited
        changecolor(settingLogout, new Color(66, 98, 124));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void cathiLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cathiLabelMouseClicked
    {//GEN-HEADEREND:event_cathiLabelMouseClicked
//        diadiemForm.initTableDiaDiem();
        caThiDTOs = caThiDAO.getList();
        caThiForm.initTable();
        jPanelThiSinh.setVisible(false);
        jPanelGiangVien.setVisible(false);
        jPanelKhoaThi.setVisible(false);
        jPanelPhongThi.setVisible(false);
        jPanelTrinhDo.setVisible(false);
        jPanelCaThi.setVisible(true);
        jPanelKetQua.setVisible(false);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_cathiLabelMouseClicked

    private void cathiLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cathiLabelMouseEntered
    {//GEN-HEADEREND:event_cathiLabelMouseEntered
        changecolor(phongthiPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_cathiLabelMouseEntered

    private void cathiLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cathiLabelMouseExited
    {//GEN-HEADEREND:event_cathiLabelMouseExited
        changecolor(phongthiPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_cathiLabelMouseExited

    private void phongthiLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_phongthiLabelMouseClicked
    {//GEN-HEADEREND:event_phongthiLabelMouseClicked
//        doanForm.initTableDoan();
//        doanForm.resetAll();
        if (phongThiForm.getjTabbedPane1().getComponentCount() == 2)
        {
            phongThiForm.getjTabbedPane1().remove(phongThiForm.getjTabbedPane1().getComponentAt(1));
            phongThiForm.getjTabbedPane1().setEnabledAt(0, true);
            phongThiForm.getjTabbedPane1().setSelectedIndex(0);
        }
        khoaThiDTOs = khoaThiDAO.getList();
        trinhDoDTOs = trinhDoDAO.getList();
        phongThiDTOs = phongThiDAO.getList();
        caThiDTOs = caThiDAO.getList();
        phieuBaoDuThiDTOs = phieuBaoDuThiDAO.getList();
        thiSinhDTOs = thiSinhDAO.getList();
        phanCongDTOs = phanCongDAO.getList();
        giaoVienDTOs = giaoVienDAO.getList();
        
        phongThiForm.initTable();
        jPanelThiSinh.setVisible(false);
        jPanelGiangVien.setVisible(false);
        jPanelKhoaThi.setVisible(false);
        jPanelPhongThi.setVisible(true);
        jPanelTrinhDo.setVisible(false);
        jPanelCaThi.setVisible(false);
        jPanelKetQua.setVisible(false);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_phongthiLabelMouseClicked

    private void phongthiLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_phongthiLabelMouseEntered
    {//GEN-HEADEREND:event_phongthiLabelMouseEntered
        changecolor(hopdongPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_phongthiLabelMouseEntered

    private void phongthiLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_phongthiLabelMouseExited
    {//GEN-HEADEREND:event_phongthiLabelMouseExited
        changecolor(hopdongPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_phongthiLabelMouseExited

    private void thisinhLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_thisinhLabelMouseClicked
    {//GEN-HEADEREND:event_thisinhLabelMouseClicked
        thiSinhDTOs = thiSinhDAO.getList();
        khoaThiDTOs = khoaThiDAO.getList();  
        trinhDoDTOs = trinhDoDAO.getList();
        //phieuBaoDuThiDTOs = phieuBaoDuThiDAO.getList();
       
        thiSinhForm.initTable();
        if (thiSinhForm.getjTabbedPane1().getComponentCount() == 3)
        {
            thiSinhForm.getjTabbedPane1().remove(thiSinhForm.getjTabbedPane1().getComponentAt(1));
            thiSinhForm.getjTabbedPane1().setEnabledAt(0, true);
            thiSinhForm.getjTabbedPane1().setSelectedIndex(0);
            thiSinhForm.getjBtnThemTS1().setEnabled(true);
            thiSinhForm.getjBtnTaoPhieu().setEnabled(false);
            thiSinhForm.getjBtnCancel1().setEnabled(false);
            thiSinhForm.getjBtnXoaTS1().setEnabled(false);           
        }
        jPanelThiSinh.setVisible(true);
        jPanelGiangVien.setVisible(false);
        jPanelKhoaThi.setVisible(false);
        jPanelPhongThi.setVisible(false);
        jPanelTrinhDo.setVisible(false);
        jPanelCaThi.setVisible(false);
        jPanelKetQua.setVisible(false);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_thisinhLabelMouseClicked

    private void thisinhLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_thisinhLabelMouseEntered
    {//GEN-HEADEREND:event_thisinhLabelMouseEntered
        changecolor(khachPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_thisinhLabelMouseEntered

    private void thisinhLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_thisinhLabelMouseExited
    {//GEN-HEADEREND:event_thisinhLabelMouseExited
        changecolor(khachPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_thisinhLabelMouseExited

    private void giaovienLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_giaovienLabelMouseClicked
    {//GEN-HEADEREND:event_giaovienLabelMouseClicked
//        nhanvienForm.loadData();
        giaoVienDTOs= giaoVienDAO.getList();
        phanCongDTOs=phanCongDAO.getList();
        giaoVienForm.initTableGV();
        jPanelThiSinh.setVisible(false);
        jPanelGiangVien.setVisible(true);
        jPanelKhoaThi.setVisible(false);
        jPanelPhongThi.setVisible(false);
        jPanelTrinhDo.setVisible(false);
        jPanelCaThi.setVisible(false);
        jPanelKetQua.setVisible(false);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_giaovienLabelMouseClicked

    private void giaovienLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_giaovienLabelMouseEntered
    {//GEN-HEADEREND:event_giaovienLabelMouseEntered
        changecolor(nhanvienPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_giaovienLabelMouseEntered

    private void giaovienLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_giaovienLabelMouseExited
    {//GEN-HEADEREND:event_giaovienLabelMouseExited
        changecolor(nhanvienPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_giaovienLabelMouseExited

    private void khoathiLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoathiLabelMouseExited
        changecolor(thisinhPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_khoathiLabelMouseExited

    private void khoathiLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoathiLabelMouseEntered
        changecolor(thisinhPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_khoathiLabelMouseEntered

    private void khoathiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoathiLabelMouseClicked
        khoaThiDTOs = khoaThiDAO.getList();
        phongThiDTOs = phongThiDAO.getList();
        thiSinhDTOs = thiSinhDAO.getList();
        khoaThiForm.initTable();
        jPanelThiSinh.setVisible(false);
        jPanelGiangVien.setVisible(false);
        jPanelKhoaThi.setVisible(true);
        jPanelPhongThi.setVisible(false);
        jPanelTrinhDo.setVisible(false);
        jPanelCaThi.setVisible(false);
        jPanelKetQua.setVisible(false);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_khoathiLabelMouseClicked

    private void ketquaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketquaLabelMouseClicked
//        chiPhiForm.initTableLoaiChiPhi();
        jPanelThiSinh.setVisible(false);
        jPanelGiangVien.setVisible(false);
        jPanelKhoaThi.setVisible(false);
        jPanelPhongThi.setVisible(false);
        jPanelTrinhDo.setVisible(false);
        jPanelCaThi.setVisible(false);
        jPanelKetQua.setVisible(true);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_ketquaLabelMouseClicked

    private void ketquaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketquaLabelMouseEntered
        changecolor(chiphiPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_ketquaLabelMouseEntered

    private void ketquaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketquaLabelMouseExited
        changecolor(chiphiPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_ketquaLabelMouseExited

    private void trinhdoLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_trinhdoLabelMouseClicked
    {//GEN-HEADEREND:event_trinhdoLabelMouseClicked
//        loaiHinhForm.initTableLH();
        phongThiDTOs = phongThiDAO.getList();
        thiSinhDTOs = thiSinhDAO.getList();
        trinhDoDTOs = trinhDoDAO.getList();
        trinhDoForm.initTable();
        jPanelThiSinh.setVisible(false);
        jPanelGiangVien.setVisible(false);
        jPanelKhoaThi.setVisible(false);
        jPanelPhongThi.setVisible(false);
        jPanelTrinhDo.setVisible(true);
        jPanelCaThi.setVisible(false);
        jPanelKetQua.setVisible(false);
//        jPanelLoaiHinh.setVisible(false);
    }//GEN-LAST:event_trinhdoLabelMouseClicked

    private void trinhdoLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_trinhdoLabelMouseEntered
    {//GEN-HEADEREND:event_trinhdoLabelMouseEntered
        // TODO add your handling code here:
        changecolor(giangvienPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_trinhdoLabelMouseEntered

    private void trinhdoLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_trinhdoLabelMouseExited
    {//GEN-HEADEREND:event_trinhdoLabelMouseExited
        // TODO add your handling code here:
        changecolor(giangvienPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_trinhdoLabelMouseExited

    public JLabel getjLabel5()
    {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5)
    {
        this.jLabel5 = jLabel5;
    }

    public JLabel getBccLabel()
    {
        return thisinhLabel;
    }

    public void setBccLabel(JLabel bccLabel)
    {
        this.thisinhLabel = bccLabel;
    }

    public JLabel getBtnHidemenu()
    {
        return btnHidemenu;
    }

    public void setBtnHidemenu(JLabel btnHidemenu)
    {
        this.btnHidemenu = btnHidemenu;
    }

    public JLabel getBtnLogout()
    {
        return btnLogout;
    }

    public void setBtnLogout(JLabel btnLogout)
    {
        this.btnLogout = btnLogout;
    }

    public JLabel getHopdongLabel()
    {
        return phongthiLabel;
    }

    public void setHopdongLabel(JLabel hopdongLabel)
    {
        this.phongthiLabel = hopdongLabel;
    }

    public JLabel getNhanvienLabel()
    {
        return khoathiLabel;
    }

    public void setNhanvienLabel(JLabel nhanvienLabel)
    {
        this.khoathiLabel = nhanvienLabel;
    }

    public JLabel getPbLabel()
    {
        return cathiLabel;
    }

    public void setPbLabel(JLabel pbLabel)
    {
        this.cathiLabel = pbLabel;
    }

    public JLabel getPhucapLabel()
    {
        return giaovienLabel;
    }

    public void setPhucapLabel(JLabel phucapLabel)
    {
        this.giaovienLabel = phucapLabel;
    }

    public JLabel getThuongphatLabel()
    {
        return ketquaLabel;
    }

    public void setThuongphatLabel(JLabel thuongphatLabel)
    {
        this.ketquaLabel = thuongphatLabel;
    }

    public JLabel getjLabelClosed()
    {
        return jLabelClosed;
    }

    public void setjLabelClosed(JLabel jLabelClosed)
    {
        this.jLabelClosed = jLabelClosed;
    }

    public JLabel getjLabelMini()
    {
        return jLabelMini;
    }

    public void setjLabelMini(JLabel jLabelMini)
    {
        this.jLabelMini = jLabelMini;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHidemenu;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel cathiLabel;
    private javax.swing.JPanel chiphiPanel;
    private javax.swing.JPanel giangvienPanel;
    private javax.swing.JLabel giaovienLabel;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel hopdongPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClosed;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCaThi;
    private javax.swing.JPanel jPanelGiangVien;
    private javax.swing.JPanel jPanelKetQua;
    private javax.swing.JPanel jPanelKhoaThi;
    private javax.swing.JPanel jPanelPhongThi;
    private javax.swing.JPanel jPanelThiSinh;
    private javax.swing.JPanel jPanelTrinhDo;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel ketquaLabel;
    private javax.swing.JPanel khachPanel;
    private javax.swing.JLabel khoathiLabel;
    private javax.swing.JPanel linehideMenu;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel nhanvienPanel;
    private javax.swing.JLabel phongthiLabel;
    private javax.swing.JPanel phongthiPanel;
    private javax.swing.JPanel settingLogout;
    private javax.swing.JLabel thisinhLabel;
    private javax.swing.JPanel thisinhPanel;
    private javax.swing.JLabel trinhdoLabel;
    // End of variables declaration//GEN-END:variables

//    public static void main (String[] args)
//    {
//        DashBoard l=new DashBoard ();
//        l.setVisible (true);
//    }
}
