/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import BUS.CongViecBUS;
import DTO.ThiSinhDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import BUS.NhanVienBUS;
//import BUS.NhanVienCongViecBUS;
//import BUS.PhongBanBUS;
//import DTO.NhanVienDTO;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Hyung
 */
public class PhieuBaoDuThi extends javax.swing.JFrame
{

    /**
     * Creates new form DSNV
     */
    int rowTbl;

    Vector tbCol = new Vector();
    DefaultTableModel tbModel;
    ThiSinhForm thiSinhForm;

    public PhieuBaoDuThi()
    {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        jBtnXacNhan.setEnabled(false);
        jBtnQuayLai.setEnabled(true);
    }
    
    public void fillTheForm(ThiSinhDTO thiSinh,String khoaThi,String trinhDo){
        jTextMaTS.setText(thiSinh.getMaThiSinh());
        jTextTenTS.setText(thiSinh.getHoTen());
        jTextSDTTS.setText(thiSinh.getSdt());
        jTextCMNDTS.setText(thiSinh.getCmnd());
        jTextNgaySinhTS.setText(thiSinh.getNgaySinh());
        jTextDiaChiTS.setText(thiSinh.getDiaChi());
        jTextEmailTS.setText(thiSinh.getMail());
        jTextKhoaThiTS.setText(khoaThi);
        
        jTextSBDTS.setText("");
        jTextMaPhongTS.setText("");
        jTextMaCaTS.setText("");
        jTextNgayThiTS.setText("");
        
        jTextTrinhDo.setText(trinhDo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel4 = new javax.swing.JPanel();
        jLbManv = new javax.swing.JLabel();
        jTextMaTS = new javax.swing.JTextField();
        jLbHonv = new javax.swing.JLabel();
        jTextTenTS = new javax.swing.JTextField();
        jBtnQuayLai = new javax.swing.JButton();
        jBtnXacNhan = new javax.swing.JButton();
        jLbHonv1 = new javax.swing.JLabel();
        jTextCMNDTS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextSBDTS = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextSDTTS = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextNgaySinhTS = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextDiaChiTS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextEmailTS = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextMaPhongTS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextMaCaTS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextNgayThiTS = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextTrinhDo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextKhoaThiTS = new javax.swing.JTextField();

        setBackground(new java.awt.Color(236, 245, 252));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(830, 500));
        setType(java.awt.Window.Type.POPUP);

        jPanel4.setBackground(new java.awt.Color(236, 245, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Báo Dự Thi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 51, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(830, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbManv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbManv.setText("<html> <body> Mã Thí Sinh<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jTextMaTS.setEditable(false);
        jTextMaTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextMaTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextMaTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextMaTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 32, 204, 30));

        jLbHonv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbHonv.setText("<html><body>Tên Thí Sinh<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbHonv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        jTextTenTS.setEditable(false);
        jTextTenTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextTenTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextTenTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextTenTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 204, 30));

        jBtnQuayLai.setBackground(new java.awt.Color(136, 193, 184));
        jBtnQuayLai.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back1_16.png"))); // NOI18N
        jBtnQuayLai.setText("Thoát");
        jBtnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnQuayLai.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnQuayLaiActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 140, 40));

        jBtnXacNhan.setBackground(new java.awt.Color(136, 193, 184));
        jBtnXacNhan.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jBtnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_checked_32.png"))); // NOI18N
        jBtnXacNhan.setText("In Phiếu ");
        jBtnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnXacNhan.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnXacNhanActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 140, 40));

        jLbHonv1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbHonv1.setText("<html><body>SÐT<span style=\"color:rgb(234, 21, 21)\"> *</span> </body> </html>");
        jPanel4.add(jLbHonv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 60, 30));

        jTextCMNDTS.setEditable(false);
        jTextCMNDTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextCMNDTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextCMNDTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextCMNDTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 204, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("<html> <body>SBD <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, 30));

        jTextSBDTS.setEditable(false);
        jTextSBDTS.setBackground(new java.awt.Color(214, 217, 223));
        jTextSBDTS.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jTextSBDTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 200, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("<html> <body>CMND <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextSDTTS.setEditable(false);
        jTextSDTTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextSDTTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextSDTTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextSDTTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 204, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("<html> <body>Ngày Sinh <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jTextNgaySinhTS.setEditable(false);
        jTextNgaySinhTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextNgaySinhTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextNgaySinhTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextNgaySinhTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 204, 30));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("<html> <body>Địa chỉ <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jTextDiaChiTS.setEditable(false);
        jTextDiaChiTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextDiaChiTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextDiaChiTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextDiaChiTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 204, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("<html> <body>Email <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jTextEmailTS.setEditable(false);
        jTextEmailTS.setForeground(new java.awt.Color(51, 51, 51));
        jTextEmailTS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextEmailTSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextEmailTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 204, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("<html> <body>Phòng Thi <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, 30));

        jTextMaPhongTS.setEditable(false);
        jTextMaPhongTS.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaPhongTS.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jTextMaPhongTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 200, 30));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("<html> <body>Ca Thi <span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 30));

        jTextMaCaTS.setEditable(false);
        jTextMaCaTS.setBackground(new java.awt.Color(214, 217, 223));
        jTextMaCaTS.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jTextMaCaTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 200, 30));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("<html> <body>Ngày Thi<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, 30));

        jTextNgayThiTS.setEditable(false);
        jTextNgayThiTS.setBackground(new java.awt.Color(214, 217, 223));
        jTextNgayThiTS.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jTextNgayThiTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 200, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("<html> <body>Trình Độ<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, 30));

        jTextTrinhDo.setEditable(false);
        jTextTrinhDo.setBackground(new java.awt.Color(214, 217, 223));
        jTextTrinhDo.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jTextTrinhDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 200, 30));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("<html> <body>Khóa Thi<span style=\"color:rgb(216, 74, 67);\">*</span> </body> </html> ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        jTextKhoaThiTS.setEditable(false);
        jTextKhoaThiTS.setBackground(new java.awt.Color(214, 217, 223));
        jTextKhoaThiTS.setForeground(new java.awt.Color(102, 102, 102));
        jPanel4.add(jTextKhoaThiTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnQuayLaiActionPerformed
    {//GEN-HEADEREND:event_jBtnQuayLaiActionPerformed
        jTextMaTS.setText("");
        jTextTenTS.setText("");
        dispose();
//        jTextTennv.setText("");
//        jTextPban.setText("");
//        jTextCviec.setText("");
    }//GEN-LAST:event_jBtnQuayLaiActionPerformed

    private void jTextTenTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextTenTSActionPerformed
    {//GEN-HEADEREND:event_jTextTenTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenTSActionPerformed

    private void jTextMaTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMaTSActionPerformed
    {//GEN-HEADEREND:event_jTextMaTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaTSActionPerformed
    public String ktra()
    {
        String temp = "";
//        if (jTextMaNV.getText().equals("")) {
//            temp += "- Vui lòng chọn loại hình!";
//        }
        return temp;
    }
    private void jBtnXacNhanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnXacNhanActionPerformed
    {//GEN-HEADEREND:event_jBtnXacNhanActionPerformed
//        if (!jBtnXacNhan.isEnabled()) {
//            System.out.println("Disabled");
//        } else {
//            if (ktra().equals("")) {
//                String maLoai = jTextMaLH.getText(), tenLoai = jTextTenLH.getText();
//                if (tourForm != null) {
//                    tourForm.getjTextLoaiHinh().setText(tenLoai);
//                    tourForm.setMaLoai(maLoai);
//                }
//                dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, ktra());
//            }
//        }

        dispose();
    }//GEN-LAST:event_jBtnXacNhanActionPerformed

    private void jTextCMNDTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextCMNDTSActionPerformed
    {//GEN-HEADEREND:event_jTextCMNDTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCMNDTSActionPerformed

    private void jTextSDTTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextSDTTSActionPerformed
    {//GEN-HEADEREND:event_jTextSDTTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSDTTSActionPerformed

    private void jTextNgaySinhTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextNgaySinhTSActionPerformed
    {//GEN-HEADEREND:event_jTextNgaySinhTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNgaySinhTSActionPerformed

    private void jTextDiaChiTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextDiaChiTSActionPerformed
    {//GEN-HEADEREND:event_jTextDiaChiTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiaChiTSActionPerformed

    private void jTextEmailTSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextEmailTSActionPerformed
    {//GEN-HEADEREND:event_jTextEmailTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailTSActionPerformed

//    public void searchlistSP(ArrayList<NhanVienDTO> nv)
//    {
//        tbModel.setRowCount(0);
//        outModel(tbModel, nv);
//    }
//    public String getTextFieldContent()
//    {
//        return bccForm.getjTextManv().getText();
//    }
//    public String getTextFieldContentLuong()
//    {
//        return luongForm.getjTextManv().getText();
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PhieuBaoDuThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PhieuBaoDuThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PhieuBaoDuThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PhieuBaoDuThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PhieuBaoDuThi().setVisible(true);
            }
        });
    }

    public JButton getjBtnQuayLai()
    {
        return jBtnQuayLai;
    }

    public void setjBtnQuayLai(JButton jBtnQuayLai)
    {
        this.jBtnQuayLai = jBtnQuayLai;
    }

  

    public JButton getjBtnXacNhan()
    {
        return jBtnXacNhan;
    }

    public void setjBtnXacNhan(JButton jBtnXacNhan)
    {
        this.jBtnXacNhan = jBtnXacNhan;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnQuayLai;
    private javax.swing.JButton jBtnXacNhan;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLbHonv;
    private javax.swing.JLabel jLbHonv1;
    private javax.swing.JLabel jLbManv;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextCMNDTS;
    private javax.swing.JTextField jTextDiaChiTS;
    private javax.swing.JTextField jTextEmailTS;
    private javax.swing.JTextField jTextKhoaThiTS;
    private javax.swing.JTextField jTextMaCaTS;
    private javax.swing.JTextField jTextMaPhongTS;
    private javax.swing.JTextField jTextMaTS;
    private javax.swing.JTextField jTextNgaySinhTS;
    private javax.swing.JTextField jTextNgayThiTS;
    private javax.swing.JTextField jTextSBDTS;
    private javax.swing.JTextField jTextSDTTS;
    private javax.swing.JTextField jTextTenTS;
    private javax.swing.JTextField jTextTrinhDo;
    // End of variables declaration//GEN-END:variables
}
